### ISSUE TITLE
package failed to build. Error in dyn.load(dllfile)

### ISSUE THREAD

**Issue by fguinot** [jchiquet/sicomore-pkg#8]
Error in dyn.load(dllfile) : 
  impossible de charger l'objet partagé '/Users/fguinot/sicomore-pkg/src/SIComORe.so':
  dlopen(/Users/fguinot/sicomore-pkg/src/SIComORe.so, 6): Symbol not found: _cWardHeaps
  Referenced from: /Users/fguinot/sicomore-pkg/src/SIComORe.so
  Expected in: flat namespace
 in /Users/fguinot/sicomore-pkg/src/SIComORe.so
Calls: <Anonymous> ... <Anonymous> -> load_dll -> library.dynam2 -> dyn.load
Exécution arrêtée

**Comment by jchiquet** [comment]
ça plante avec la version master courante ? Ou suite à des modifications que tu as faites ?

**Comment by fguinot** [comment]
J'avais pas testé le build avant de faire la modif, j'aurais peut -être
dû...
Après j'ai juste ajouté un argument dans le fonction, ça devrait pas avoir
d'impact normalement...
Je regarde ça demain et je te dis

Le mer. 18 mars 2020 à 18:32, Julien Chiquet <notifications@github.com> a
écrit :

**Comment by fguinot** [comment]
Salut Julien,

J'ai revert mon commit pour revenir à ta version du package et j'ai essayé
de build (avec le bouton Install and Restart de l'onglet build dans
Rstudio) mais j'ai toujours le même message d'erreur:
impossible de charger l'objet partagé
'/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-sicomore-pkg/00new/SIComORe/libs/SIComORe.so':

dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-sicomore-pkg/00new/SIComORe/libs/SIComORe.so,
6): Symbol not found: _cWardHeaps
  Referenced from:
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-sicomore-pkg/00new/SIComORe/libs/SIComORe.so
  Expected in: flat namespace
 in
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-sicomore-pkg/00new/SIComORe/libs/SIComORe.so
Erreur : le chargement a échoué

Par contre quand j'installe le package depuis github directement ça
fonctionne avec devtools::install_github("jchiquet/sicomore-pkg").

Il doit me manquer une librairie sur mon ordi pour pouvoir compiler
directement depuis Rstudio peut-être?

Florent

Le mer. 18 mars 2020 à 19:23, Florent Guinot <guinotflorent@gmail.com> a
écrit :

**Comment by jchiquet** [comment]
C'est très étrange car les check fonctionne sur travis. Ça doit plutôt être
lié à ton installation.

Tu veux pas tout nettoyer ? tes .so et autres ?

--
Julien Chiquet
Senior Researcher in Statistics, INRAE

https://jchiquet.github.io/
orcid.org/0000-0002-3629-3429
